### ISSUE TITLE
New Feature: To-Do Page added features

### ISSUE THREAD

**Issue by jonaisahhh** [reynaldicheok/ETI-CA2#9]
Additional features to be added into To-Do Page

- [x] To-Do items filtered to Users. i.e. Only To-Do items created by Owner is shown.
- [x] Addition and deletion of To-Do items auto archived instead of the current manual process.
- [x] All To-Do items to have a timestamp added upon creation automatically by the application.

**Comment by reynaldicheok** [comment]
completed with documentation
